// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdkCihkKjTZ_SzYKcxq8tw6xXzWMxbxxI',
    appId: '1:967409265452:web:aa381d521eaf118b2cda89',
    messagingSenderId: '967409265452',
    projectId: 'course1-fa6a9',
    authDomain: 'course1-fa6a9.firebaseapp.com',
    storageBucket: 'course1-fa6a9.appspot.com',
    measurementId: 'G-VE0LC70GK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8oqqDLI4nIoRqyf08jqYoBI-Ewn5YvTQ',
    appId: '1:967409265452:android:73c3edde5594feeb2cda89',
    messagingSenderId: '967409265452',
    projectId: 'course1-fa6a9',
    storageBucket: 'course1-fa6a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbw5pBy2v3GNNPOIa7HUhUzK7iFw7dj_8',
    appId: '1:967409265452:ios:2c49578ea693fb212cda89',
    messagingSenderId: '967409265452',
    projectId: 'course1-fa6a9',
    storageBucket: 'course1-fa6a9.appspot.com',
    iosBundleId: 'com.example.s2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbw5pBy2v3GNNPOIa7HUhUzK7iFw7dj_8',
    appId: '1:967409265452:ios:8dca4941e2ae19082cda89',
    messagingSenderId: '967409265452',
    projectId: 'course1-fa6a9',
    storageBucket: 'course1-fa6a9.appspot.com',
    iosBundleId: 'com.example.s2.RunnerTests',
  );
}
